spring:
  cloud:
    gateway:
      routes:
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/recommendations/**
  cors:
    allowed-origins: "http://localhost:4200"
    allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
    allowed-headers: "Content-Type, Authorization"
  discovery:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
