server:
  port: 8761
spring:
  application:
    name: eureka-server
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
